# Generated by Django 2.2.6 on 2019-10-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmeup', '0002_auto_20191023_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email'),
        ),
    ]
