# Generated by Django 2.2.6 on 2019-10-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmeup', '0003_auto_20191026_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.BooleanField(),
        ),
    ]
