# Generated by Django 2.2.6 on 2020-01-01 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizmeup', '0005_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_a', models.CharField(max_length=3)),
                ('subject_b', models.CharField(max_length=3)),
                ('contact', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='stud_contact', to=settings.AUTH_USER_MODEL)),
                ('email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='stud_email', to=settings.AUTH_USER_MODEL, verbose_name='email')),
                ('username', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='stud_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
