# Generated by Django 2.2.6 on 2020-01-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmeup', '0007_auto_20200101_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='username',
        ),
    ]
